### ISSUE TITLE
Callback scope

### ISSUE THREAD

**Issue by Noino** [freqdec/fd-slider#1]
Callbacks are run in global scope which is.. well awkward.

run in scope of the input:
fd-slider.js:~450
- function callback
                                      for(var i = 0, func; func = callbacks[type][i]; i++) {
                                              func.call(cbObj.elem, cbObj);
                                      };

**Comment by freqdec** [comment]
Thanks my man - shall add it this weekend.

**Comment by freqdec** [comment]
Callbacks now ran in the scope of the original form element
