### ISSUE TITLE
Finalise also on stopDrag?

### ISSUE THREAD

**Issue by 0x6a68** [freqdec/fd-slider#13]
Shouldnt the stopDrag function also call finalise or am i doing it wrong? sidenote i am not using the tween.

**Comment by freqdec** [comment]
Hi designaholic,

The finalise callback only gets fired when the tween animation has ended, it's not plugged into the drag & drop code at all. I could get the code to fire a "dragStop" event if this would help?

**Comment by 0x6a68** [comment]
as long as i can use the cb func: finalise, to sync the active value via ajax, i am fine with it

**Comment by freqdec** [comment]
I've added dragstart and dragend callbacks on the drag handle. You can also (probably easier) just use the update callback to sync values to the server though. This is called each time the associated form element has it's value updated.
