### ISSUE TITLE
What is the license for fd-slider

### ISSUE THREAD

**Issue by stepheneb** [freqdec/fd-slider#17]
What is the license for fd-slider? 

I didn't see any license mentioned in the README or fd-slider.js.

Thanks

**Comment by freqdec** [comment]
Hi Stephen. Here we go:

/*! Unobtrusive Slider Control / HTML5 Input Range polyfill - MIT/GPL2 @freqdec */

**Comment by stepheneb** [comment]
Thanks!

The license reference was a bit smaller than I was expecting when I was scanning the project ;-)

**Comment by freqdec** [comment]
I know - it's a lazy license!
