### ISSUE TITLE
usetSet value not passed in callback object

### ISSUE THREAD

**Issue by freqdec** [freqdec/fd-slider#18]
No callbacks currently receive the userSet parameter. The doc states that they do.

**Comment by getdave** [comment]
Thanks for raising this bug. I didn't want to go ahead and raise on Github before I'd 100% checked with you.

**Comment by freqdec** [comment]
Fixed in latest version! Good catch getdave...

**Comment by getdave** [comment]
Not a problem. Glad to help.
