### ISSUE TITLE
Change eventhandler not triggered in IE9

### ISSUE THREAD

**Issue by aukevanleeuwen** [freqdec/fd-slider#22]
It seems the 'change' event handler that I have registered is lost in IE9. I'm using jQuery to do something like:

```
$(rangeInput).on("change", function(event) {
    window.alert("changed...");
});
```

If I trigger `fdSlider.onDomReady();` before of after that I'm not getting my changes in IE9.

The weird thing is that if I show the corresponding input field (by disabling the `display: none;` style) I can see that that field is actually being updated with the correct values when I move the slider. It's just that I don't get any change events apparently.

Firefox (11) , **IE8**, **IE7** work fine.

**Comment by freqdec** [comment]
I think this must be the way in which jQuery attaches the onchange event as it works fine in the demo page in IE9 (the second slider has an onchange event registered).

I shall have a look at the jQuery source whenever I've got a moment to see if this can be fixed.

**Comment by hitsthings** [comment]
I looked into this a bit, but didn't get very far. Thought I'd share the relevant code to save you some time:

jQuery triggers change as a special event, which means it doesn't fire handlers because it assumes the special special handler does it. The special handler does a lot of crazy things for checkboxes and radios, but mostly otherwise keeps it the same.

Search https://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.js for "jQuery.event.special.change" and you'll see the relevant code.

I'll probably try to debug through it later and see what's happening.

**Comment by jholster** [comment]
I'm facing the same problem with Batman.js; with IE9, no 'change' event fires. Batman.js doesn't use jQuery bindings so the problem is not jQuery-only related.

**Comment by tomchiverton** [comment]
Doesn't appear to work in similar scenario in IE8 WinXP either.

**Comment by paulirish** [comment]
Does this approach fair any better to run the handlers? http://stackoverflow.com/a/832121/89484

**Comment by backflip** [comment]
I was able to fix this by preferring `createEvent` (using `dispatchEvent`) over `createEventObject` (using `fireEvent`). Tested in IE8 and IE9.

Before:

```
if(typeof(document.createEventObject) != 'undefined') {
    try {
        e = document.createEventObject();
        inp.fireEvent('on' + type.toLowerCase(), e);
    } catch(err){ }
} else if(typeof(document.createEvent) != 'undefined') {
    e = document.createEvent('HTMLEvents');
    e.initEvent(type, true, true);
    inp.dispatchEvent(e);
}
```

**After**:

```
if(typeof(document.createEvent) != 'undefined') {
    e = document.createEvent('HTMLEvents');
    e.initEvent(type, true, true);
    inp.dispatchEvent(e);
} else if(typeof(document.createEventObject) != 'undefined') {
    try {
        e = document.createEventObject();
        inp.fireEvent('on' + type.toLowerCase(), e);
    } catch(err){ }
}
```

**Comment by fordie** [comment]
Thanks @backflip that solved my issue. And there was me thinking my code was at fault :D Glad to pin the blame on IE

**Comment by freqdec** [comment]
@backflip many thanks indeed.
