### ISSUE TITLE
is there a reload/scan/buildFromElement(id) function?

### ISSUE THREAD

**Issue by Pomax** [freqdec/fd-slider#28]
I'd like to use fd-slider in a way that doesn't require content generation scripts to become dependent on it, so the ones I have do callbacks after generating new sliders. I'd like to use fd-slider to then take the html element created and work its magic on that element to make it compatible with IE9 and FF, but it doesn't look like there's a function that lets me do something like:

```
var inp = document.createElement("input");
inp.type = "range";
fdsliter.convertToSlider(inp);
```

Can this already be done and am I just not finding it in the docs, or is this effectively a feature request for something that would have to be added to fd-slider?

**Comment by freqdec** [comment]
I'm afraid it can't be done. You have to add the element to the dom and then call the createSlider method. I shall look into it though...

**Comment by freqdec** [comment]
Hold on, I'm being stupid. Just call the fdSlider.rescanDocument() method. This will scan the DOM for inputs and polyfill them where necessary. Wow, talk about not knowing your own code.
