### ISSUE TITLE
extra styles

### ISSUE THREAD

**Issue by paulirish** [freqdec/fd-slider#3]
I needed this

`.fd-slider bar { width: auto; }`

**Comment by paulirish** [comment]
also.. i typically needed to trigger the change event that i had bound to the original `<input>` .. doing that the Right way catches your own binds so its pretty nasty.

something to think about..

**Comment by freqdec** [comment]
Hi Paul, I'm working on the native event calls (amongst other updates) - should drop next week (just had a kid so time at keyboard limited!). 

Thanks for the input...

**Comment by paulirish** [comment]
awesome! that's great news.. :D (on both accounts!)

btw i'm launching http://mothereffinghsl.com in a few hours which features your slider again :)

**Comment by freqdec** [comment]
Two months late with the fix. Not good at all!

width:auto added to default CSS file.
