### ISSUE TITLE
Check if "disabled" attribute is true or "disabled"

### ISSUE THREAD

**Issue by backflip** [freqdec/fd-slider#32]
The test whether the input is disabled should account for getAttribute returning "disabled".

Before:

```
if(inp.getAttribute("disabled") == true)
```

After:

```
if(inp.getAttribute("disabled") == true || inp.getAttribute("disabled") == "disabled")
```

**Comment by freqdec** [comment]
Thanks for the addition. Much appreciated.

**Comment by backflip** [comment]
You're welcome! I might even figure out that pull request thing someday...
