### ISSUE TITLE
Split out oldid styles to separate sheet

### ISSUE THREAD

**Issue by nschonni** [freqdec/fd-slider#37]
Since some of the oldie rules are completely commented out, it might make sense to move them to a separate sheet where the are actually implemented.

**Comment by freqdec** [comment]
Hi Nick, you should really use a minified version - there's a little utility provided in /css-generator/ that enables you to generate a minified CSS file suitable for installation on your server.

**Comment by nschonni** [comment]
We import your files into Sass because of some optimization that aren't backwards compatible (like base64 encoding images don't work in old IE) and we target the specific versions of IE. From that Sass we produce 2 sheets ([oldie overrides](https://github.com/wet-boew/wet-boew/blob/master/src/js/sass/includes/_slider-ie.scss) and [modern browsers](https://github.com/wet-boew/wet-boew/blob/master/src/js/sass/includes/_slider.scss)) that are bundled with other third party CSS and then minified.

EDIT: sorry for the bad proof reading
