### ISSUE TITLE
Weird Unicode character in source

### ISSUE THREAD

**Issue by mathiasbynens** [freqdec/fd-slider#4]
See https://github.com/freqdec/fd-slider/blob/master/js/fd-slider.js#L36

Here’s a screenshot: http://i.imgur.com/vETbA.png

**Comment by freqdec** [comment]
How strange! It shouldn't crash the script but I'll look into it tonight when I'm at home.

Thanks for the warning!

**Comment by freqdec** [comment]
Hi Mathias - fixed in the latest snapshot. Thanks for pointing it out.
