### ISSUE TITLE
there are 2 function valueSet(tf) {},does it a bug? so the function setValueSet(sliderId, tf) doesn't work

### ISSUE THREAD

**Issue by coffeexy** [freqdec/fd-slider#45]
there are 2 function valueSet(tf) {},does it a bug?
so the function setValueSet(sliderId, tf) doesn't work

358 function valueSet(tf) {
            tf = !!tf;
            if(tf != userSet) {
                userSet = tf;
                valueToPixels(getWorkingValueFromInput());
            }
        }
1146 function valueSet(tf) {
            userSet = !!tf;
        }

**Comment by freqdec** [comment]
Hi, it was indeed a bug! I've removed one of the offending functions. Many thanks for the input.
