### ISSUE TITLE
IE7 error: Invalid argument at line 1008

### ISSUE THREAD

**Issue by mathiasbynens** [freqdec/fd-slider#6]
IE7 is throwing an “invalid argument” error on this line: https://github.com/freqdec/fd-slider/blob/master/js/fd-slider.js#L1008

![Screenshot of the issue](http://i.imgur.com/Dq7ws.jpg)

I think it’s because `handle.offsetLeft` is returning negative values in IE7.

Removing that line effectively seems to prevent the error from being thrown, but then of course the slider bars are broken.

Note that your script works fine on its own; only now that I added it to a page with a lot of other scripts in it (not mine) this issue comes up. Before I dive into all the other scripts used on that page, could you please tell me if you’ve seen this before by any chance? Any ideas on how to fix it?

**Comment by mathiasbynens** [comment]
OMG, finally found what was causing the issue:

``` css
.ie7 * { zoom: 1; }
```

WHAT IS THIS I DONT EVEN

**Comment by freqdec** [comment]
Hi Mathias,

It appears I might have to double check the offset's are available before
using them e.g.

rangeBar.style["width"] = (handle.offsetLeft || 0) + "px";

I've never seen this one before - the error message is, as usual, not
particularly helpful.

I initially thought that I may have declared "handle" as a global variable
and that it was getting overwritten by another script but a quick look at
the code debunks that theory; "handle" is declared local to the slider
object and cannot be overwritten.

Sorry I can't be of more use! I always feel like an asshat when sending "I
have no idea" replies.

Shall look into it this weekend in more detail.

**Comment by mathiasbynens** [comment]
```
rangeBar.style["width"] = (handle.offsetLeft || 0) + "px";
```

That wouldn’t work, since it won’t use the `0` if `handle.offsetLeft` gets a negative value.

In this case, the problem was caused by this horrible piece of CSS:

``` css
.ie7 * { zoom: 1; }
```

Somehow, this causes `handle` to get a negative `offsetLeft` in IE7.

It’s definitely not a bug in FD-Slider, but if there is a way to work around it (I doubt it) it may be worthwhile to do so.

**Comment by freqdec** [comment]
Dam, you're fast man...

That's a very nasty piece of CSS indeed. Perhaps a Math.max inclusion might
be in order:

rangeBar.style["width"] = Math.max(0, (handle.offsetLeft || 0)) + "px";

Shall add it to git this weekend.

Thanks again,
Brian.

**Comment by mathiasbynens** [comment]
I haven’t come across a situation where `handle.offsetLeft` is falsy, so I’m not sure the `|| 0` is really needed.

Using `Math.max()` would prevent IE7 from throwing the error, but then the slider wouldn’t work if `handle.offsetLeft` is negative, which it shouldn’t be unless you use really weird CSS like the rule set I came across. Perhaps it would be useful to throw an error from within fd-slider, saying “Negative value for `offsetLeft` detected — are you using `zoom: 1` where you shouldn’t?” Or maybe it’s not worth the hassle for this edge case, I don’t know. Just throwing it out there.

Thanks!
