### ISSUE TITLE
set slider from new value from input field

### ISSUE THREAD

**Issue by jjsarton** [freqdec/fd-slider#9]
How may I set sliders to a new value. I have tried fdSlider.setValueSet('id1');... fdSlider.setValueSet('id6');,... This don't work for all fields and not always for the same fields.

**Comment by jjsarton** [comment]
I have an application which allow to set some parameters via fd-slider. The form can be called for various targets and I have to set the value for the various input fields while opening the form popup. Unfortunatelly refreshing the slider via fdSlider.updateSlider(id); is not sufficient, the aria value remain to the old value which is wrong. In oder to get this working I had to call fdSlider.stepDown(id,1); fdSlider.stepUp(id,1); or   fdSlider.stepUp(id,1);fdSlider.stepDown(id,1); according to the allowed max value and the actual value. May you improve the fd-slider code so that the aria value is set correctly if a new value is set ?

**Comment by freqdec** [comment]
Yeah, no problem. Looks like you found a bug as the ARIA values should be automatically updated when calling the updateSlider() method (but only if the input value has changed). Shall look into it.

**Comment by freqdec** [comment]
OK, I was trying to be too clever in the code. Shall update tonight with fix. Well spotted indeed sir! Thanks for the bug report.

**Comment by jjsarton** [comment]
I will try the new code within a few days, at this time I have some other occupations.

**Comment by jjsarton** [comment]
The release 0635a70 seem to work as expected. For the previous version I had to initialize fd-slider from my own onload event, this now OK so that I don't need to modify your code.
